database:
  dbname: tau
  username: tau
  password: 
  
collegefootballstats:
  apikey:

server:
  address: localhost
  port: 44080
  certfile: /server/resources/cert.pem
  keyfile: /server/resources/key.pem
  cert_password: 
