# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_player_success_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPlayerSuccessDialog(object):
    def setupUi(self, AddPlayerSuccessDialog):
        AddPlayerSuccessDialog.setObjectName("AddPlayerSuccessDialog")
        AddPlayerSuccessDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddPlayerSuccessDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(AddPlayerSuccessDialog)
        self.label.setGeometry(QtCore.QRect(80, 100, 241, 61))
        self.label.setObjectName("label")

        self.retranslateUi(AddPlayerSuccessDialog)
        self.buttonBox.accepted.connect(AddPlayerSuccessDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddPlayerSuccessDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddPlayerSuccessDialog)

    def retranslateUi(self, AddPlayerSuccessDialog):
        _translate = QtCore.QCoreApplication.translate
        AddPlayerSuccessDialog.setWindowTitle(_translate("AddPlayerSuccessDialog", "Success"))
        self.label.setText(_translate("AddPlayerSuccessDialog", "Player successfully added to team."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPlayerSuccessDialog = QtWidgets.QDialog()
    ui = Ui_AddPlayerSuccessDialog()
    ui.setupUi(AddPlayerSuccessDialog)
    AddPlayerSuccessDialog.show()
    sys.exit(app.exec_())
