# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/another_window_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnotherWindow(object):
    def setupUi(self, AnotherWindow):
        AnotherWindow.setObjectName("AnotherWindow")
        AnotherWindow.resize(1069, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_xml/../images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("ui_xml/../images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        AnotherWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AnotherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.view_team_tab = QtWidgets.QWidget()
        self.view_team_tab.setObjectName("view_team_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.view_team_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_6 = QtWidgets.QComboBox(self.view_team_tab)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_6, 0, 2, 1, 1)
        self.view_players = QtWidgets.QTableWidget(self.view_team_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_players.sizePolicy().hasHeightForWidth())
        self.view_players.setSizePolicy(sizePolicy)
        self.view_players.setMinimumSize(QtCore.QSize(1029, 0))
        self.view_players.setObjectName("view_players")
        self.view_players.setColumnCount(15)
        self.view_players.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.view_players.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.view_players.setHorizontalHeaderItem(14, item)
        self.view_players.horizontalHeader().setCascadingSectionResizes(True)
        self.view_players.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.view_players, 1, 0, 1, 3)
        self.comboBox_5 = QtWidgets.QComboBox(self.view_team_tab)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_4.addWidget(self.comboBox_5, 0, 0, 1, 1)
        self.create_new_team_3 = QtWidgets.QPushButton(self.view_team_tab)
        self.create_new_team_3.setObjectName("create_new_team_3")
        self.gridLayout_4.addWidget(self.create_new_team_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.view_team_tab, "")
        self.player_stats_tab = QtWidgets.QWidget()
        self.player_stats_tab.setObjectName("player_stats_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.player_stats_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.available_players = QtWidgets.QTableWidget(self.player_stats_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.available_players.sizePolicy().hasHeightForWidth())
        self.available_players.setSizePolicy(sizePolicy)
        self.available_players.setMinimumSize(QtCore.QSize(1029, 0))
        self.available_players.setObjectName("available_players")
        self.available_players.setColumnCount(15)
        self.available_players.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.available_players.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.available_players.setHorizontalHeaderItem(14, item)
        self.available_players.horizontalHeader().setCascadingSectionResizes(True)
        self.available_players.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.available_players, 1, 0, 1, 3)
        self.comboBox_2 = QtWidgets.QComboBox(self.player_stats_tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.create_new_team = QtWidgets.QPushButton(self.player_stats_tab)
        self.create_new_team.setObjectName("create_new_team")
        self.gridLayout_2.addWidget(self.create_new_team, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.player_stats_tab)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.player_stats_tab, "")
        self.profile_tab = QtWidgets.QWidget()
        self.profile_tab.setObjectName("profile_tab")
        self.pushButton = QtWidgets.QPushButton(self.profile_tab)
        self.pushButton.setGeometry(QtCore.QRect(588, 10, 141, 25))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.profile_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tfl_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfl_edit.sizePolicy().hasHeightForWidth())
        self.tfl_edit.setSizePolicy(sizePolicy)
        self.tfl_edit.setClearButtonEnabled(False)
        self.tfl_edit.setObjectName("tfl_edit")
        self.gridLayout.addWidget(self.tfl_edit, 3, 3, 1, 1)
        self.receptions_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receptions_edit.sizePolicy().hasHeightForWidth())
        self.receptions_edit.setSizePolicy(sizePolicy)
        self.receptions_edit.setObjectName("receptions_edit")
        self.gridLayout.addWidget(self.receptions_edit, 3, 1, 1, 1)
        self.fg_percentage_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fg_percentage_edit.sizePolicy().hasHeightForWidth())
        self.fg_percentage_edit.setSizePolicy(sizePolicy)
        self.fg_percentage_edit.setObjectName("fg_percentage_edit")
        self.gridLayout.addWidget(self.fg_percentage_edit, 7, 3, 1, 1)
        self.punting_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.punting_edit.sizePolicy().hasHeightForWidth())
        self.punting_edit.setSizePolicy(sizePolicy)
        self.punting_edit.setObjectName("punting_edit")
        self.gridLayout.addWidget(self.punting_edit, 6, 3, 1, 1)
        self.yards_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yards_edit.sizePolicy().hasHeightForWidth())
        self.yards_edit.setSizePolicy(sizePolicy)
        self.yards_edit.setObjectName("yards_edit")
        self.gridLayout.addWidget(self.yards_edit, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.settings_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        self.turnovers_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnovers_edit.sizePolicy().hasHeightForWidth())
        self.turnovers_edit.setSizePolicy(sizePolicy)
        self.turnovers_edit.setObjectName("turnovers_edit")
        self.gridLayout.addWidget(self.turnovers_edit, 6, 1, 1, 1)
        self.touchdowns_label = QtWidgets.QLabel(self.settings_tab)
        self.touchdowns_label.setObjectName("touchdowns_label")
        self.gridLayout.addWidget(self.touchdowns_label, 5, 0, 1, 1)
        self.interceptions_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interceptions_edit.sizePolicy().hasHeightForWidth())
        self.interceptions_edit.setSizePolicy(sizePolicy)
        self.interceptions_edit.setObjectName("interceptions_edit")
        self.gridLayout.addWidget(self.interceptions_edit, 4, 3, 1, 1)
        self.title_label = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setStyleSheet("font: 26pt \"Ubuntu\";")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 0, 1, 4)
        self.fg_percentage_label = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fg_percentage_label.sizePolicy().hasHeightForWidth())
        self.fg_percentage_label.setSizePolicy(sizePolicy)
        self.fg_percentage_label.setObjectName("fg_percentage_label")
        self.gridLayout.addWidget(self.fg_percentage_label, 7, 2, 1, 1)
        self.fumbles_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fumbles_edit.sizePolicy().hasHeightForWidth())
        self.fumbles_edit.setSizePolicy(sizePolicy)
        self.fumbles_edit.setObjectName("fumbles_edit")
        self.gridLayout.addWidget(self.fumbles_edit, 5, 3, 1, 1)
        self.submit_button = QtWidgets.QPushButton(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_button.sizePolicy().hasHeightForWidth())
        self.submit_button.setSizePolicy(sizePolicy)
        self.submit_button.setObjectName("submit_button")
        self.gridLayout.addWidget(self.submit_button, 9, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.receptions_label = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receptions_label.sizePolicy().hasHeightForWidth())
        self.receptions_label.setSizePolicy(sizePolicy)
        self.receptions_label.setObjectName("receptions_label")
        self.gridLayout.addWidget(self.receptions_label, 3, 0, 1, 1)
        self.sacks_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sacks_edit.sizePolicy().hasHeightForWidth())
        self.sacks_edit.setSizePolicy(sizePolicy)
        self.sacks_edit.setObjectName("sacks_edit")
        self.gridLayout.addWidget(self.sacks_edit, 7, 1, 1, 1)
        self.punting_label = QtWidgets.QLabel(self.settings_tab)
        self.punting_label.setObjectName("punting_label")
        self.gridLayout.addWidget(self.punting_label, 6, 2, 1, 1)
        self.yards_label = QtWidgets.QLabel(self.settings_tab)
        self.yards_label.setObjectName("yards_label")
        self.gridLayout.addWidget(self.yards_label, 4, 0, 1, 1)
        self.touchdowns_edit = QtWidgets.QLineEdit(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touchdowns_edit.sizePolicy().hasHeightForWidth())
        self.touchdowns_edit.setSizePolicy(sizePolicy)
        self.touchdowns_edit.setObjectName("touchdowns_edit")
        self.gridLayout.addWidget(self.touchdowns_edit, 5, 1, 1, 1)
        self.sacks_label = QtWidgets.QLabel(self.settings_tab)
        self.sacks_label.setObjectName("sacks_label")
        self.gridLayout.addWidget(self.sacks_label, 7, 0, 1, 1)
        self.fumbles_label = QtWidgets.QLabel(self.settings_tab)
        self.fumbles_label.setObjectName("fumbles_label")
        self.gridLayout.addWidget(self.fumbles_label, 5, 2, 1, 1)
        self.interceptions_label = QtWidgets.QLabel(self.settings_tab)
        self.interceptions_label.setObjectName("interceptions_label")
        self.gridLayout.addWidget(self.interceptions_label, 4, 2, 1, 1)
        self.turnovers_label = QtWidgets.QLabel(self.settings_tab)
        self.turnovers_label.setObjectName("turnovers_label")
        self.gridLayout.addWidget(self.turnovers_label, 6, 0, 1, 1)
        self.tfl_label = QtWidgets.QLabel(self.settings_tab)
        self.tfl_label.setObjectName("tfl_label")
        self.gridLayout.addWidget(self.tfl_label, 3, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.settings_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.settings_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        AnotherWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnotherWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AnotherWindow)

    def retranslateUi(self, AnotherWindow):
        _translate = QtCore.QCoreApplication.translate
        AnotherWindow.setWindowTitle(_translate("AnotherWindow", "Roster Rookies"))
        self.comboBox_6.setItemText(0, _translate("AnotherWindow", "Week 1"))
        self.comboBox_6.setItemText(1, _translate("AnotherWindow", "Week 2"))
        self.comboBox_6.setItemText(2, _translate("AnotherWindow", "Week 3"))
        self.comboBox_6.setItemText(3, _translate("AnotherWindow", "Week 4"))
        self.comboBox_6.setItemText(4, _translate("AnotherWindow", "Week 5"))
        self.comboBox_6.setItemText(5, _translate("AnotherWindow", "Week 6"))
        self.comboBox_6.setItemText(6, _translate("AnotherWindow", "Week 7"))
        self.comboBox_6.setItemText(7, _translate("AnotherWindow", "Week 8"))
        self.comboBox_6.setItemText(8, _translate("AnotherWindow", "Week 9"))
        self.comboBox_6.setItemText(9, _translate("AnotherWindow", "Week 10"))
        self.comboBox_6.setItemText(10, _translate("AnotherWindow", "Week 11"))
        self.comboBox_6.setItemText(11, _translate("AnotherWindow", "Week 12"))
        self.comboBox_6.setItemText(12, _translate("AnotherWindow", "Week 13"))
        self.comboBox_6.setItemText(13, _translate("AnotherWindow", "Week 14"))
        self.view_players.setSortingEnabled(True)
        item = self.view_players.horizontalHeaderItem(1)
        item.setText(_translate("AnotherWindow", "Position"))
        item = self.view_players.horizontalHeaderItem(2)
        item.setText(_translate("AnotherWindow", "Player Name"))
        item = self.view_players.horizontalHeaderItem(3)
        item.setText(_translate("AnotherWindow", "Score"))
        item = self.view_players.horizontalHeaderItem(4)
        item.setText(_translate("AnotherWindow", "Receptions"))
        item = self.view_players.horizontalHeaderItem(5)
        item.setText(_translate("AnotherWindow", "Total Yards"))
        item = self.view_players.horizontalHeaderItem(6)
        item.setText(_translate("AnotherWindow", "Touchdowns"))
        item = self.view_players.horizontalHeaderItem(7)
        item.setText(_translate("AnotherWindow", "Turnovers Lost"))
        item = self.view_players.horizontalHeaderItem(8)
        item.setText(_translate("AnotherWindow", "Sacks"))
        item = self.view_players.horizontalHeaderItem(9)
        item.setText(_translate("AnotherWindow", "Tackles for Loss"))
        item = self.view_players.horizontalHeaderItem(10)
        item.setText(_translate("AnotherWindow", "Interceptions"))
        item = self.view_players.horizontalHeaderItem(11)
        item.setText(_translate("AnotherWindow", "Fumbles Recovered"))
        item = self.view_players.horizontalHeaderItem(12)
        item.setText(_translate("AnotherWindow", "Punting Yards"))
        item = self.view_players.horizontalHeaderItem(13)
        item.setText(_translate("AnotherWindow", "FG Percentage"))
        item = self.view_players.horizontalHeaderItem(14)
        item.setText(_translate("AnotherWindow", "Injury Status"))
        self.create_new_team_3.setText(_translate("AnotherWindow", "Create New Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view_team_tab), _translate("AnotherWindow", "View Team"))
        self.available_players.setSortingEnabled(True)
        item = self.available_players.horizontalHeaderItem(1)
        item.setText(_translate("AnotherWindow", "Position"))
        item = self.available_players.horizontalHeaderItem(2)
        item.setText(_translate("AnotherWindow", "Player Name"))
        item = self.available_players.horizontalHeaderItem(3)
        item.setText(_translate("AnotherWindow", "Score"))
        item = self.available_players.horizontalHeaderItem(4)
        item.setText(_translate("AnotherWindow", "Receptions"))
        item = self.available_players.horizontalHeaderItem(5)
        item.setText(_translate("AnotherWindow", "Total Yards"))
        item = self.available_players.horizontalHeaderItem(6)
        item.setText(_translate("AnotherWindow", "Touchdowns"))
        item = self.available_players.horizontalHeaderItem(7)
        item.setText(_translate("AnotherWindow", "Turnovers Lost"))
        item = self.available_players.horizontalHeaderItem(8)
        item.setText(_translate("AnotherWindow", "Sacks"))
        item = self.available_players.horizontalHeaderItem(9)
        item.setText(_translate("AnotherWindow", "Tackles for Loss"))
        item = self.available_players.horizontalHeaderItem(10)
        item.setText(_translate("AnotherWindow", "Interceptions"))
        item = self.available_players.horizontalHeaderItem(11)
        item.setText(_translate("AnotherWindow", "Fumbles Recovered"))
        item = self.available_players.horizontalHeaderItem(12)
        item.setText(_translate("AnotherWindow", "Punting Yards"))
        item = self.available_players.horizontalHeaderItem(13)
        item.setText(_translate("AnotherWindow", "FG Percentage"))
        item = self.available_players.horizontalHeaderItem(14)
        item.setText(_translate("AnotherWindow", "Injury Status"))
        self.comboBox_2.setItemText(0, _translate("AnotherWindow", "Week 1"))
        self.comboBox_2.setItemText(1, _translate("AnotherWindow", "Week 2"))
        self.comboBox_2.setItemText(2, _translate("AnotherWindow", "Week 3"))
        self.comboBox_2.setItemText(3, _translate("AnotherWindow", "Week 4"))
        self.comboBox_2.setItemText(4, _translate("AnotherWindow", "Week 5"))
        self.comboBox_2.setItemText(5, _translate("AnotherWindow", "Week 6"))
        self.comboBox_2.setItemText(6, _translate("AnotherWindow", "Week 7"))
        self.comboBox_2.setItemText(7, _translate("AnotherWindow", "Week 8"))
        self.comboBox_2.setItemText(8, _translate("AnotherWindow", "Week 9"))
        self.comboBox_2.setItemText(9, _translate("AnotherWindow", "Week 10"))
        self.comboBox_2.setItemText(10, _translate("AnotherWindow", "Week 11"))
        self.comboBox_2.setItemText(11, _translate("AnotherWindow", "Week 12"))
        self.comboBox_2.setItemText(12, _translate("AnotherWindow", "Week 13"))
        self.comboBox_2.setItemText(13, _translate("AnotherWindow", "Week 14"))
        self.create_new_team.setText(_translate("AnotherWindow", "Create New Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.player_stats_tab), _translate("AnotherWindow", "Available Players"))
        self.pushButton.setText(_translate("AnotherWindow", "Change Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile_tab), _translate("AnotherWindow", "Profile"))
        self.touchdowns_label.setText(_translate("AnotherWindow", "Touchdowns:"))
        self.title_label.setText(_translate("AnotherWindow", "Fill the weighted values below:"))
        self.fg_percentage_label.setText(_translate("AnotherWindow", "Field Goal Percentage:"))
        self.submit_button.setText(_translate("AnotherWindow", "Submit"))
        self.receptions_label.setText(_translate("AnotherWindow", "Receptions:"))
        self.punting_label.setText(_translate("AnotherWindow", "Punting Yards:"))
        self.yards_label.setText(_translate("AnotherWindow", "Total Yards:"))
        self.sacks_label.setText(_translate("AnotherWindow", "Sacks:"))
        self.fumbles_label.setText(_translate("AnotherWindow", "Fumbles Recovered:"))
        self.interceptions_label.setText(_translate("AnotherWindow", "Interceptions:"))
        self.turnovers_label.setText(_translate("AnotherWindow", "Turnovers Lost:"))
        self.tfl_label.setText(_translate("AnotherWindow", "Tackles for Loss:"))
        self.label.setText(_translate("AnotherWindow", "Enter 0.0 for no weight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("AnotherWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnotherWindow = QtWidgets.QMainWindow()
    ui = Ui_AnotherWindow()
    ui.setupUi(AnotherWindow)
    AnotherWindow.show()
    sys.exit(app.exec_())
