# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_xml/create_new_team_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateNewTeamDialog(object):
    def setupUi(self, CreateNewTeamDialog):
        CreateNewTeamDialog.setObjectName("CreateNewTeamDialog")
        CreateNewTeamDialog.resize(701, 524)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateNewTeamDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 189, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(CreateNewTeamDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(CreateNewTeamDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.team_name_edit = QtWidgets.QLineEdit(CreateNewTeamDialog)
        self.team_name_edit.setObjectName("team_name_edit")
        self.verticalLayout.addWidget(self.team_name_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 189, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateNewTeamDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CreateNewTeamDialog)
        self.buttonBox.accepted.connect(CreateNewTeamDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateNewTeamDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateNewTeamDialog)

    def retranslateUi(self, CreateNewTeamDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateNewTeamDialog.setWindowTitle(_translate("CreateNewTeamDialog", "Create New Team"))
        self.label.setText(_translate("CreateNewTeamDialog", "Please Enter a New Team Name"))
