# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'failure_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FailureDialog(object):
    def setupUi(self, FailureDialog):
        FailureDialog.setObjectName("FailureDialog")
        FailureDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(FailureDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(FailureDialog)
        self.label.setGeometry(QtCore.QRect(26, 66, 341, 131))
        self.label.setText("")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(FailureDialog)
        self.buttonBox.rejected.connect(FailureDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(FailureDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FailureDialog)

    def retranslateUi(self, FailureDialog):
        _translate = QtCore.QCoreApplication.translate
        FailureDialog.setWindowTitle(_translate("FailureDialog", "Failure"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FailureDialog = QtWidgets.QDialog()
    ui = Ui_FailureDialog()
    ui.setupUi(FailureDialog)
    FailureDialog.show()
    sys.exit(app.exec_())
