# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_replaced_player_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectReplacedPlayerDialog(object):
    def setupUi(self, SelectReplacedPlayerDialog):
        SelectReplacedPlayerDialog.setObjectName("SelectReplacedPlayerDialog")
        SelectReplacedPlayerDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectReplacedPlayerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(SelectReplacedPlayerDialog)
        self.buttonBox.accepted.connect(SelectReplacedPlayerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectReplacedPlayerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectReplacedPlayerDialog)

    def retranslateUi(self, SelectReplacedPlayerDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectReplacedPlayerDialog.setWindowTitle(_translate("SelectReplacedPlayerDialog", "Select Player to Replace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectReplacedPlayerDialog = QtWidgets.QDialog()
    ui = Ui_SelectReplacedPlayerDialog()
    ui.setupUi(SelectReplacedPlayerDialog)
    SelectReplacedPlayerDialog.show()
    sys.exit(app.exec_())
