# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'success_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuccessDialog(object):
    def setupUi(self, SuccessDialog):
        SuccessDialog.setObjectName("SuccessDialog")
        SuccessDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(SuccessDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(SuccessDialog)
        self.label.setGeometry(QtCore.QRect(26, 66, 341, 131))
        self.label.setText("")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(SuccessDialog)
        self.buttonBox.rejected.connect(SuccessDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(SuccessDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SuccessDialog)

    def retranslateUi(self, SuccessDialog):
        _translate = QtCore.QCoreApplication.translate
        SuccessDialog.setWindowTitle(_translate("SuccessDialog", "Success"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SuccessDialog = QtWidgets.QDialog()
    ui = Ui_SuccessDialog()
    ui.setupUi(SuccessDialog)
    SuccessDialog.show()
    sys.exit(app.exec_())
